<?php

namespace App\Filament\Resources\InsuranceProvidersResource\Pages;

use App\Filament\Resources\InsuranceProvidersResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;

class EditInsuranceProviders extends EditRecord
{
    protected static string $resource = InsuranceProvidersResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        createLog("Company Settings Updated by User: #" . Auth::user()->name);

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
