<?php

namespace App\Filament\Resources\VehicleResource\Pages;

use App\Filament\Resources\VehicleResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;

class EditVehicle extends EditRecord
{
    protected static string $resource = VehicleResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $recipient = auth()->user();
        Notification::make()
            ->title('Saved successfully')
            ->sendToDatabase($recipient);

    $this->dispatch('play-notification-sound');

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
